name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
   runs-on: ubuntu-latest

   services:  
    image: mongo
    ports: ["27017:27017"]
  
   steps:
     - name: Checkout Respository
       uses: actions/checkout@v6

     - name: Setup Node js
       uses: actions@setup-node@v3
       with:
        node-version: "18"

     - name: Wating for mongodb to be ready
       run: 
          until nc -z localhost 27017; do
          echo "Waiting for mongoDB..."
          sleep 2
          done
           echo "MongoDB is up"

     - name: Seed MongoDB
       working-directory: ./backend
       run: |
         npm install 
         node seedTasksData.js
  
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v6

      - name: Setup Node js
        uses: actions@setup-node@v3
        with:
         node-version: "18"

      - name: Install depedency for backend
        run: npm install 
      
      - name: Running backend test
        run: npm test 